name: SNAPRed
channels:
- conda-forge
- default
- mantid/label/nightly
dependencies:
- python=3.10
- pip
- pydantic>=1.10,<2
- mantidworkbench>=6.7
- qtpy
- pre-commit
- pytest
- pytest-qt
- pytest-cov
- flake8
- versioningit
- anaconda-client
- conda-build
- conda-verify
- setuptools
- sphinx
- sphinx_rtd_theme=1.2.*
- types-pyyaml
- python-build
- boa
- pycifrw
- pip:
  - check-wheel-contents=0.4.0
